version: '3.3'
services:
    transmission:
        build: 
          context: .
        cap_add:
            - NET_ADMIN
        volumes:
            # Path/to/download/folder:/data
            - '/srv/mydisk/films/torrents:/data'

            # Path/to/openvpn/conf/folder/:/etc/openvpn/custom/
            # This folder must contain:
            #   - [OPENVPN_CONFIG].ovpn             -- the ovpn config file, depending on env var below
            #   - ca.crt client.crt client.key      -- ovpn files used in the ovpn file
            # personnally I hardcoded paths (ie. /etc/openvpn/custom/ca.crt instead of ca.crt) in the ovpn file to avoid errors.
            - '/srv/mydisk/compose/transmission/openvpn/Swiss/:/etc/openvpn/custom/'

            - /etc/localtime:/etc/localtime:ro
        environment:
            - OPENVPN_PROVIDER=custom
            - OPENVPN_CONFIG=XXXXX            # name of the openvpn file, without ".ovpn"
            - OPENVPN_USERNAME=XXXXXXXXXXXXX  # username to connect
            - OPENVPN_PASSWORD=XXXXXXXXXXXXX  # password to connect
            - LOCAL_NETWORK=192.168.0.0/16    # local network to not send through the tunnel
            - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
            - HEALTH_CHECK_HOST=google.com
        dns:
          - 1.1.1.1
          - 1.0.0.1
        logging:
            driver: json-file
            options:
                max-size: 10m
        ports:
            - '9091:9091'
            - "8888:8888"
        restart: always
